/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_B1_11 (coord C13), KEY_BTUP */

/* Symbols to be used with GPIO driver */
#define RTE_KEY_BTUP_GPIO                                                  GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_KEY_BTUP_GPIO_PIN                                                27U   /*!< GPIO pin number */
#define RTE_KEY_BTUP_GPIO_PIN_MASK                                   (1U << 27U)   /*!< GPIO pin mask */

/* GPIO_B1_09 (coord A13), KEY_BTLF */

/* Symbols to be used with GPIO driver */
#define RTE_KEY_BTLF_GPIO                                                  GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_KEY_BTLF_GPIO_PIN                                                25U   /*!< GPIO pin number */
#define RTE_KEY_BTLF_GPIO_PIN_MASK                                   (1U << 25U)   /*!< GPIO pin mask */

/* GPIO_B1_10 (coord B13), KEY_BTOK */

/* Symbols to be used with GPIO driver */
#define RTE_KEY_BTOK_GPIO                                                  GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_KEY_BTOK_GPIO_PIN                                                26U   /*!< GPIO pin number */
#define RTE_KEY_BTOK_GPIO_PIN_MASK                                   (1U << 26U)   /*!< GPIO pin mask */

/* GPIO_B1_08 (coord A12), KEY_BTRT */

/* Symbols to be used with GPIO driver */
#define RTE_KEY_BTRT_GPIO                                                  GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_KEY_BTRT_GPIO_PIN                                                24U   /*!< GPIO pin number */
#define RTE_KEY_BTRT_GPIO_PIN_MASK                                   (1U << 24U)   /*!< GPIO pin mask */

/* GPIO_B1_07 (coord B12), KEY_BTDN */

/* Symbols to be used with GPIO driver */
#define RTE_KEY_BTDN_GPIO                                                  GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_KEY_BTDN_GPIO_PIN                                                23U   /*!< GPIO pin number */
#define RTE_KEY_BTDN_GPIO_PIN_MASK                                   (1U << 23U)   /*!< GPIO pin mask */

/* GPIO_B1_06 (coord C12), BEEP_EN */

/* Symbols to be used with GPIO driver */
#define RTE_BEEP_EN_GPIO                                                   GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_BEEP_EN_GPIO_PIN                                                 22U   /*!< GPIO pin number */
#define RTE_BEEP_EN_GPIO_PIN_MASK                                    (1U << 22U)   /*!< GPIO pin mask */

/* GPIO_B1_05 (coord D12), SERVO_EN */

/* Symbols to be used with GPIO driver */
#define RTE_SERVO_EN_GPIO                                                  GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_SERVO_EN_GPIO_PIN                                                21U   /*!< GPIO pin number */
#define RTE_SERVO_EN_GPIO_PIN_MASK                                   (1U << 21U)   /*!< GPIO pin mask */

/* GPIO_B1_04 (coord E12), KEY_BTSE */

/* Symbols to be used with GPIO driver */
#define RTE_KEY_BTSE_GPIO                                                  GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_KEY_BTSE_GPIO_PIN                                                20U   /*!< GPIO pin number */
#define RTE_KEY_BTSE_GPIO_PIN_MASK                                   (1U << 20U)   /*!< GPIO pin mask */

/* GPIO_B1_02 (coord C11), MOTOR_EN */

/* Symbols to be used with GPIO driver */
#define RTE_MOTOR_EN_GPIO                                                  GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_MOTOR_EN_GPIO_PIN                                                18U   /*!< GPIO pin number */
#define RTE_MOTOR_EN_GPIO_PIN_MASK                                   (1U << 18U)   /*!< GPIO pin mask */

/* GPIO_B1_01 (coord B11), KEY_BTME */

/* Symbols to be used with GPIO driver */
#define RTE_KEY_BTME_GPIO                                                  GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_KEY_BTME_GPIO_PIN                                                17U   /*!< GPIO pin number */
#define RTE_KEY_BTME_GPIO_PIN_MASK                                   (1U << 17U)   /*!< GPIO pin mask */

/* GPIO_B0_15 (coord E11), TOF0_XHT */

/* Symbols to be used with GPIO driver */
#define RTE_TOF0_XHT_GPIO                                                  GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_TOF0_XHT_GPIO_PIN                                                15U   /*!< GPIO pin number */
#define RTE_TOF0_XHT_GPIO_PIN_MASK                                   (1U << 15U)   /*!< GPIO pin mask */

/* GPIO_B0_14 (coord E10), TOF0_INT */

/* Symbols to be used with GPIO driver */
#define RTE_TOF0_INT_GPIO                                                  GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_TOF0_INT_GPIO_PIN                                                14U   /*!< GPIO pin number */
#define RTE_TOF0_INT_GPIO_PIN_MASK                                   (1U << 14U)   /*!< GPIO pin mask */

/* GPIO_B0_13 (coord D10), TOF1_XHT */

/* Symbols to be used with GPIO driver */
#define RTE_TOF1_XHT_GPIO                                                  GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_TOF1_XHT_GPIO_PIN                                                13U   /*!< GPIO pin number */
#define RTE_TOF1_XHT_GPIO_PIN_MASK                                   (1U << 13U)   /*!< GPIO pin mask */

/* GPIO_B0_12 (coord C10), TOF1_INT */

/* Symbols to be used with GPIO driver */
#define RTE_TOF1_INT_GPIO                                                  GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_TOF1_INT_GPIO_PIN                                                12U   /*!< GPIO pin number */
#define RTE_TOF1_INT_GPIO_PIN_MASK                                   (1U << 12U)   /*!< GPIO pin mask */

/* GPIO_B0_11 (coord A10), PWM2_B2 */

/* GPIO_B0_10 (coord D9), PWM2_A2 */

/* GPIO_B0_09 (coord C9), PWM2_B1 */

/* GPIO_B0_07 (coord A9), PWM2_B0 */

/* GPIO_B0_06 (coord A8), PWM2_A0 */

/* GPIO_B0_05 (coord B8), I2C2_SDA */

/* GPIO_B0_04 (coord C8), I2C2_SCL */

/* GPIO_B0_03 (coord D8), SPI4_SCK */

/* GPIO_B0_02 (coord E8), SPI4_SDO */

/* GPIO_B0_01 (coord E7), DISP_BKL */

/* Symbols to be used with GPIO driver */
#define RTE_DISP_BKL_GPIO                                                  GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_DISP_BKL_GPIO_PIN                                                 1U   /*!< GPIO pin number */
#define RTE_DISP_BKL_GPIO_PIN_MASK                                    (1U << 1U)   /*!< GPIO pin mask */

/* GPIO_B0_00 (coord D7), DISP_D_C */

/* Symbols to be used with GPIO driver */
#define RTE_DISP_D_C_GPIO                                                  GPIO2   /*!< GPIO peripheral base pointer */
#define RTE_DISP_D_C_GPIO_PIN                                                 0U   /*!< GPIO pin number */
#define RTE_DISP_D_C_GPIO_PIN_MASK                                    (1U << 0U)   /*!< GPIO pin mask */

/* GPIO_B1_12 (coord D13), UART5_TX */

/* GPIO_B1_13 (coord D14), UART5_RX */

/* GPIO_B1_15 (coord B14), PWM4_A3 */

/* GPIO_B1_14 (coord C14), PWM4_B3 */

/* GPIO_EMC_41 (coord C7), DISP_RST */

/* Symbols to be used with GPIO driver */
#define RTE_DISP_RST_GPIO                                                  GPIO3   /*!< GPIO peripheral base pointer */
#define RTE_DISP_RST_GPIO_PIN                                                27U   /*!< GPIO pin number */
#define RTE_DISP_RST_GPIO_PIN_MASK                                   (1U << 27U)   /*!< GPIO pin mask */

/* GPIO_SD_B0_00 (coord J4), SDHC_CMD */

/* GPIO_SD_B0_01 (coord J3), SDHC_CLK */

/* GPIO_SD_B0_02 (coord J1), SDHC_D0 */

/* GPIO_SD_B0_03 (coord K1), SDHC_D1 */

/* GPIO_SD_B0_04 (coord H2), SDHC_D2 */

/* GPIO_SD_B0_05 (coord J2), SDHC_D3 */

/* GPIO_SD_B1_00 (coord L5), UART4_TX */

/* GPIO_SD_B1_01 (coord M5), UART4_RX */

/* GPIO_SD_B1_02 (coord M3), TCS_INT */

/* Symbols to be used with GPIO driver */
#define RTE_TCS_INT_GPIO                                                   GPIO3   /*!< GPIO peripheral base pointer */
#define RTE_TCS_INT_GPIO_PIN                                                  2U   /*!< GPIO pin number */
#define RTE_TCS_INT_GPIO_PIN_MASK                                     (1U << 2U)   /*!< GPIO pin mask */

/* GPIO_SD_B1_03 (coord M4), IMU_INT */

/* Symbols to be used with GPIO driver */
#define RTE_IMU_INT_GPIO                                                   GPIO3   /*!< GPIO peripheral base pointer */
#define RTE_IMU_INT_GPIO_PIN                                                  3U   /*!< GPIO pin number */
#define RTE_IMU_INT_GPIO_PIN_MASK                                     (1U << 3U)   /*!< GPIO pin mask */

/* GPIO_SD_B1_04 (coord P2), I2C1_SCL */

/* GPIO_SD_B1_05 (coord N3), I2C1_SDA */

/* GPIO_AD_B1_15 (coord J14), CAM_D2 */

/* GPIO_AD_B1_14 (coord G12), CAM_D3 */

/* GPIO_AD_B1_13 (coord H11), CAM_D4 */

/* GPIO_AD_B1_12 (coord H12), CAM_D5 */

/* GPIO_AD_B1_11 (coord J13), CAM_D6 */

/* GPIO_AD_B1_10 (coord L13), CAM_D7 */

/* GPIO_AD_B1_09 (coord M13), CAM_D8 */

/* GPIO_AD_B1_08 (coord H13), CAM_D9 */

/* GPIO_AD_B1_07 (coord K10), CAM_HREF */

/* GPIO_AD_B1_06 (coord J12), CAM_VSNC */

/* GPIO_AD_B1_05 (coord K12), CAM_XCLK */

/* GPIO_AD_B1_04 (coord L12), CAM_PCLK */

/* GPIO_AD_B1_03 (coord M12), CAM_RST */

/* Symbols to be used with GPIO driver */
#define RTE_CAM_RST_GPIO                                                   GPIO1   /*!< GPIO peripheral base pointer */
#define RTE_CAM_RST_GPIO_PIN                                                 19U   /*!< GPIO pin number */
#define RTE_CAM_RST_GPIO_PIN_MASK                                    (1U << 19U)   /*!< GPIO pin mask */

/* GPIO_AD_B1_02 (coord L11), MOTOR_IR */

/* GPIO_AD_B1_01 (coord K11), VOLT_BAT */

/* GPIO_AD_B1_00 (coord J11), MOTOR_IL */

/* GPIO_AD_B0_15 (coord L10), SERVO_IB */

/* GPIO_AD_B0_14 (coord H14), SERVO_IF */

/* GPIO_AD_B0_12 (coord K14), UART1_TX */

/* GPIO_AD_B0_13 (coord L14), UART1_RX */

/* GPIO_AD_B0_07 (coord F12), SWCLK */

/* GPIO_AD_B0_06 (coord E14), SWDIO */

/* GPIO_AD_B0_05 (coord G14), BOOT_SEL1 */

/* GPIO_AD_B0_04 (coord F11), BOOT_SEL0 */

/* GPIO_AD_B0_08 (coord F13), ENC_LA */

/* GPIO_AD_B0_09 (coord F14), ENC_LB */

/* GPIO_AD_B0_11 (coord G10), ENCO_RA */

/* GPIO_AD_B0_10 (coord G13), ENC_RB */

/* GPIO_AD_B0_03 (coord G11), LED_USR */

/* Symbols to be used with GPIO driver */
#define RTE_LED_USR_GPIO                                                   GPIO1   /*!< GPIO peripheral base pointer */
#define RTE_LED_USR_GPIO_PIN                                                  3U   /*!< GPIO pin number */
#define RTE_LED_USR_GPIO_PIN_MASK                                     (1U << 3U)   /*!< GPIO pin mask */

/* GPIO_AD_B0_02 (coord M11), LED_BUSG */

/* Symbols to be used with GPIO driver */
#define RTE_LED_BUSG_GPIO                                                  GPIO1   /*!< GPIO peripheral base pointer */
#define RTE_LED_BUSG_GPIO_PIN                                                 2U   /*!< GPIO pin number */
#define RTE_LED_BUSG_GPIO_PIN_MASK                                    (1U << 2U)   /*!< GPIO pin mask */

/* GPIO_AD_B0_01 (coord H10), KEY_BTUR */

/* Symbols to be used with GPIO driver */
#define RTE_KEY_BTUS_GPIO                                                  GPIO1   /*!< GPIO peripheral base pointer */
#define RTE_KEY_BTUS_GPIO_PIN                                                 1U   /*!< GPIO pin number */
#define RTE_KEY_BTUS_GPIO_PIN_MASK                                    (1U << 1U)   /*!< GPIO pin mask */

/* GPIO_AD_B0_00 (coord M14), LED_BUSR */

/* Symbols to be used with GPIO driver */
#define RTE_LED_BUSR_GPIO                                                  GPIO1   /*!< GPIO peripheral base pointer */
#define RTE_LED_BUSR_GPIO_PIN                                                 0U   /*!< GPIO pin number */
#define RTE_LED_BUSR_GPIO_PIN_MASK                                    (1U << 0U)   /*!< GPIO pin mask */

/* GPIO_B0_08 (coord B9), PWM2_A1 */

/* GPIO_B1_00 (coord A11), MOTOR_FLT */

/* GPIO_B1_03 (coord D11), SERVO_FLT */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RTEPIN_AllPin(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SDRAM(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void FLASH(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
